server:
  port: 8090

spring:
  application:
    name: app-spring-ai

  ai:
    google:
      genai:
        api-key: ${GOOGLE_API_KEY}
        chat:
          options:
            model: ${GOOGLE_CHAT_MODEL}
            temperature: 0.5
        embedding:
          api-key: ${GOOGLE_API_KEY}

    vectorstore:
      weaviate:
        host: localhost:8080
        scheme: http